### ISSUE TITLE
Where should GNUstep.sh be sourced?

### ISSUE THREAD

**Issue by tedchoward** [AgoraDesktop/AgoraInstaller#15]
Currently the `startx` script requires that the GNUstep variables be set, which means that `GNUstep.sh` needs to be sourced. What approach should we take?

1. Documentation: just tell the user that they have to source `GNUstep.sh`
2. Add the line to `.xinitrc`
3. Add the line to `.profile`
4. Something else?

**Comment by KyleCardoza** [comment]
Isn't there a global .profile that gets sourced before the user's .profile? Seems like it should be in that.

**Comment by KyleCardoza** [comment]
Yes, it's /etc/profile. That's where it should go.

**Comment by KyleCardoza** [comment]
Actually, strike that -- all we need to do is symlink the GNUstep.sh file to /etc/profile.d/GNUstep.sh, and the existing /etc/profile will load it automatically. Working on that now.
