### ISSUE TITLE
Installed system does not work if user's shell is zsh

### ISSUE THREAD

**Issue by KyleCardoza** [AgoraDesktop/AgoraInstaller#17]
The default /etc/profile is for sh and bash; zsh doesn't even look at it. Apparently it does look for /etc/zprofile, so maybe we could patch that if it exists or provide one from the installer? macOS switched to zsh as the primary shell for users a long time ago, and frankly I agree with that choice in the general sense.

**Comment by tedchoward** [comment]
FWIW, Slackware has `/etc/zprofile` as a symlink to `/etc/profile`

**Comment by tedchoward** [comment]
Yeah, in their package, they have this `doinst.sh` script (that runs when the package installs)
```bash
if ! grep zsh etc/shells 1> /dev/null 2> /dev/null; then
  echo "/bin/zsh" >> etc/shells
fi
if [ ! -e etc/zprofile ]; then
  ( cd etc ; ln -sf profile zprofile )
fi
```

**Comment by KyleCardoza** [comment]
Unfortunately that won't work for us because the syntax for doing in `zsh` what `/etc/profile` does is different. We'd need a custom one.

**Comment by tedchoward** [comment]
What's different about it? I thought zsh was fully Bourne compatible.

**Comment by KyleCardoza** [comment]
Try sourcing the FreeBSD /etc/profile from zsh.
