### ISSUE TITLE
Should zsh become the default user shell in Agora?

### ISSUE THREAD

**Issue by KyleCardoza** [AgoraDesktop/AgoraInstaller#22]
zsh has been the default user shell on macOS since Catalina -- and I see no really great reason why not to do so as well, it's a great shell, and the user is still free to choose another if they really want to.

It would add one package to the dependencies, and whatever configuration was needed, plus we'd have to fix it somehow so gnustep-make works right.

**Comment by tedchoward** [comment]
I've been using zsh as my shell for years now, so this works for me.
